meta_product_name: "StockOwl"
meta_title: "StockOwl - Learn to invest by emulating the master "
meta_description: "Are you seeking reliable resources to assist in your daily trading as you work towards maximum returns.

Lucky, we at StockOwl have compiled quarterly data from the S.E.C. F13 forms filed by America's top investors to bring the knowledge you need to trade like
the masters.

Join us by signing up for a free account, and get started on your investment journey with us."
meta_image: "stockowl_homepage_desktop.png"                       # should exist in `app/assets/images/`
